config/routes.rb
Rails.application.routes.draw do
  get 'cocktails/namerake'
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end
  resources :doses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, :dependent => :restrict_with_error

  validates :name, uniqueness: true, presence: true
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true

  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def edit
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end
  def update
    cocktail = Cocktail.find(params[:id])
    if cocktail.update(cocktail_params)
      redirect_to cocktail_path(@cocktail)
    else
      render :edit
    end
  end
  def destroy
    @cocktail.destroy!

    redirect_to cocktails_path
  end

  private

    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end


    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :photo_cache)
    end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @ingredient = Ingredient.all
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose = @dose.cocktail
    @dose.destroy!

    redirect_to cocktails_path(@cocktail)
  end

  private

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/372959/pexels-photo-372959.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb');">
  <div class="banner-content">
    <div class="text-center padded"><h1>Mister Cocktail</h1>
      <h4>Find the best recipes for your favorite cocktails</h4>
<!--       <span class="fa fa-angle-double-down fa-5x" aria-hidden="true"></span>
 -->      <%= link_to "Create a cocktail", new_cocktail_path, class: "btn" %>
    </div>
  </div>
</div>

app/views/cocktails/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <% if @cocktail.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/_list.html.erb
<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
        <td><%= link_to 'Delete', cocktail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/edit.html.erb
<%= render 'form' %>

app/views/cocktails/index.html.erb
<%= render 'banner' %>

<div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>

    <div class="col-xs-12 col-sm-4">
      <div class="card text-center">
          <%= link_to cocktail_path(cocktail), class: "a" do %>
    <% photo = cocktail.photo? ? cl_image_path(cocktail.photo, height: 300, width: 400, crop: :fill) : 'http://healthyrise.com/wp-content/uploads/2016/07/Cocktail-7.jpg'%>

        <div class="card-header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= photo %>')"></div>
        <div class="card-category"><h4 class="cocktail-name"><%= cocktail.name %></h4></div>
      </div>
    <% end %>
    </div>
      <% end %>
  </div>

</div>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>

<%= render 'form', cocktail: @cocktail %>

<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <p>
        <strong>Name:</strong>
        <%= @cocktail.name %>
      </p>

      <p>
        <strong>Dose:</strong>
        <% @cocktail.doses.each do |dose| %>
          <p>
            <%= dose.description  %>
            <%= dose.ingredient.name %>
            </p>
        <% end %>
      </p>


      <%= simple_form_for([@cocktail,@dose]) do |f| %>

        <% if @dose.errors %>
          <% @dose.errors.messages.each do |error|  %>
            Error: <%= error  %>
          <% end %>
        <% end %>

        <%= f.input :description, placeholder: '20 cl of...' %>
        <%= f.input :ingredient_id, collection: Ingredient.all %>

        <%= f.submit 'Create', class: 'btn btn-primary' %>
      <% end %>


      <%= link_to 'Edit', edit_cocktail_path(@cocktail) %> |
      <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for([@cocktail,@dose]) do |f| %>

  <% if @dose.errors %>
    <% @dose.errors.messages.each do |error|  %>
      Error: <%= error  %>
    <% end %>
  <% end %>

  <%= f.input :description, placeholder: '20 cl of...' %>
  <%= f.input :ingredient_id, collection: Ingredient.all %>

  <%= f.submit 'Create', class: 'btn btn-primary' %>
<% end %>

app/views/doses/new.html.erb
<%= render 'form', dose: @dose %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">

    <%= image_tag 'logo' %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="" class="navbar-wagon-item navbar-wagon-link">Host</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Trips</a>
    <a href="" class="navbar-wagon-item navbar-wagon-link">Messages</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mister Cocktail</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>Mister Cocktail</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link href="https://fonts.googleapis.com/css?family=Montserrat|Poiret+One" rel="stylesheet">
  </head>

  <body>

    <%= yield %>
    <div class="container">
      <%#= render 'footer' %>
    </div>
  </body>
</html>